// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzzlssxlqlrwpkgjevwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6emxzc3hscWxyd3BrZ2pldndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDg5MzYsImV4cCI6MjA2NTU4NDkzNn0.W_fAw77SlsGbUX27XBtkUZW7GwzK9CGtTNgcm3gtaXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);